# Generated by Django 5.0.6 on 2024-08-07 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_hashtag_article_hashtags'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='type',
            field=models.CharField(choices=[('none', 'None'), ('carousel', 'Carousel')], default='none', max_length=10),
        ),
    ]
